language: java
jdk:
  - openjdk11
dist: trusty
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
      - CODECOV_TOKEN=:adf18aa6-d8ce-4bd6-9143-204f7dd01e2c
